# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfAgFVnyPP8uzSxXrJnKIALJ_-ce2dMv
"""

import pandas as pd
df = pd.DataFrame({'Ism': ['Zulayho', 'Nigora', 'Sarvinoz', 'Abduvohid', 'Elshodbek',
                           'Bahmanyor', 'Asilbek', 'Otabek', 'Shaxrullo', 'Diyorjon'],
                   'Familya': ['Qadamova', 'Sobirova', 'Yusupova', 'Erqoziyev', 'Rozaliyev',
                               'Soliyev', 'Burxonov', 'Xabibullayev', 'Hamidullayev', 'Mamadaliyev'],
                   'Yoshi': ['28', '24', '18', '19', '19', '19', '19', '19', '19', '19'],
                   'Kursi': ['4', '3', '1', '2', '2', '2', '2', '2', '2', '2']})

print(df)

df.to_excel('hisobot.xlsx', index=False, sheet_name='Sheet1')